version: 0.2

phases:
  pre_build:
    commands:
      - echo ">>> Pre build OK"
  build:
    commands:
      - echo ">>> Build OK - no Docker build needed"
  post_build:
    commands:
      - echo ">>> Post build completed successfully"
